version : "3.9"
services : 
  db:
    image: nouchka/sqlite3:latest
    volumes : 
      - ./data/db:/var/lib
  website:
    build : .
    command : bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    volumes : 
      - .:/code
    ports :
      - "8000:8000"
    depends_on:
      - database



#python manage.py makemigrations
#python manage.py migrate
#python manage.py runserver




#networks : 
#  internalntwrk:
#    driver : bridge

